import type { ProductSku, ScenarioAssumptions } from "../types/models";

export const defaultScenario: ScenarioAssumptions = {
  name: "Base Case",
  mode: "tacosGoal",
  forecastMode: "flat",
  forecastDays: 30,
  velocityMultiplier: 1,
  globalTacosGoal: 0.09,
  globalCouponPercent: 0,
  globalAdSpendChangePercent: 0,
  globalPriceChangePercent: 0,
  globalCogsChangePercent: 0,
  globalFbaFeeChangePercent: 0,
  globalReferralFeePercent: null,
  shippingToAmazonPerUnit: null,
  storageFeePerUnit: null,
  skuOverrides: {},
  parentTargets: {},
};

export const sampleSkus: ProductSku[] = [
  {
    asin: "B097QF7HVH",
    sku: "10621RELYTE.STRLEMJAR",
    title: "Hydration Electrolyte Mix - Strawberry Lemonade",
    listedPrice: 45.95,
    unitsSold: 19970,
    totalSales: 917539.58,
    referralFeePerUnit: 6.6,
    fbaFeePerUnit: 4.84,
    storageFeePerUnit: 0.09,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.4,
    cogsPerUnit: 6.14,
    adSpend: 26133.53,
  },
  {
    asin: "B08QV7Q6QX",
    sku: "RELYTE.WLJAR",
    title: "Hydration Electrolyte Mix - Watermelon Lime",
    listedPrice: 45.93,
    unitsSold: 14358,
    totalSales: 659450.61,
    referralFeePerUnit: 6.6,
    fbaFeePerUnit: 4.84,
    storageFeePerUnit: 0.05,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.4,
    cogsPerUnit: 5.93,
    adSpend: 95228.07,
  },
  {
    asin: "B088G2F4ZJ",
    sku: "RELYTE.LLJAR-FBA",
    title: "Electrolyte Mix - Lemon Lime",
    listedPrice: 45.9,
    unitsSold: 15049,
    totalSales: 690757.11,
    referralFeePerUnit: 6.6,
    fbaFeePerUnit: 5.29,
    storageFeePerUnit: 0.06,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.4,
    cogsPerUnit: 6.15,
    adSpend: 10816.62,
  },
  {
    asin: "B071FNYFWW",
    sku: "RSG16-stickerless",
    title: "Fine Sea Salt 16 Ounce Pouch",
    listedPrice: 8.24,
    unitsSold: 41262,
    totalSales: 339845.82,
    referralFeePerUnit: 1.24,
    fbaFeePerUnit: 3.55,
    storageFeePerUnit: 0.07,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.4,
    cogsPerUnit: 0.74,
    adSpend: 42194.8,
  },
  {
    asin: "B08VNQHNB5",
    sku: "RELYTE.LLSTICK-FBA",
    title: "Electrolyte Mix Lemon Lime - 30 Stick Packs",
    listedPrice: 40.99,
    unitsSold: 2293,
    totalSales: 93990.07,
    referralFeePerUnit: 6.15,
    fbaFeePerUnit: 5.25,
    storageFeePerUnit: 0.15,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.4,
    cogsPerUnit: 8.3,
    adSpend: 23824.73,
  },
  {
    asin: "B0LOWMARGIN",
    sku: "WATCH-MARGIN",
    title: "Sample Thin Margin SKU",
    listedPrice: 18.99,
    unitsSold: 850,
    totalSales: 16141.5,
    referralFeePerUnit: 2.85,
    fbaFeePerUnit: 5.6,
    storageFeePerUnit: 0.12,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.55,
    cogsPerUnit: 7.5,
    adSpend: 1800,
  },
  {
    asin: "B0UNPROFIT",
    sku: "FIX-ME",
    title: "Sample Unprofitable SKU",
    listedPrice: 12.99,
    unitsSold: 460,
    totalSales: 5975.4,
    referralFeePerUnit: 1.95,
    fbaFeePerUnit: 5.1,
    storageFeePerUnit: 0.1,
    labelingFeePerUnit: 0,
    shippingToAmazonPerUnit: 0.5,
    cogsPerUnit: 5.25,
    adSpend: 1100,
  },
];
